# Site settings
baseurl = "https://example.org/"
themesDir = "../.."
languageCode = "en-us"
theme = "light-hugo"

title = "Light Hugo"
author = "John Doe"

[Params]
  description = "Describe your website"
  email = "john@example.org"
  github = "tblyler"
  twitter = "tonyblyler"
  linkedin = "johndoe"
  facebook = "johndoe"
  logo = "/images/logo.png"
